Repository rockyhawk64/CommandPanels, pull requests merged in 2024-05, with the labels that each got.

#314 CRITICAL HOT FIX 1.8-1.12
  src/me/rockyhawk/commandpanels/generatepanels/GenUtils.java
Labels: bug, critical

#312 Animated titles and give-item expansion.
  src/me/rockyhawk/commandpanels/commandtags/tags/other/SpecialTags.java
  src/me/rockyhawk/commandpanels/commandtags/tags/standard/ItemTags.java
  src/me/rockyhawk/commandpanels/generatepanels/GenUtils.java
  src/me/rockyhawk/commandpanels/openpanelsmanager/OpenGUI.java
  src/me/rockyhawk/commandpanels/playerinventoryhandler/InventorySaver.java
Labels: bug, enhancement, critical

#313 Reimplement MC Version Checks and add Warning at Startup.
  src/me/rockyhawk/commandpanels/CommandPanels.java
  src/me/rockyhawk/commandpanels/MinecraftVersions.java
Labels: enhancement
